name: ba-thesis
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6.6
  - numpy=1.14.5
  - pandas=0.23.4
  - pytorch-cpu=0.4.0
  - pip=10.0.1
  - torchvision=0.2.1
  - pip:
    - torch==0.4.0
